### ISSUE TITLE
No messages being sent

### ISSUE THREAD

**Issue by minicoz** [Blavkentropy1/Ban-SoulseekLeechers#3]
No messages are being sent to the users that are banned. Even when options are enabled.

You arent calling the send_message() function anywhere.

**Comment by minicoz** [comment]
I opened a pr to fix

**Comment by Blavkentropy1** [comment]
I have merged that. Thanks for fixing that. 

I never send messages, so I didn't realize I broke it haha.

**Comment by Blavkentropy1** [comment]
Closed, as the pull request was pushed. Thanks again.

**Comment by ngs428** [comment]
This certainly works now. I was banned for 30 minutes because it sent so many messages.  :)
